# CMake generated Testfile for 
# Source directory: /opt/lxl/c++/logAnalyzer/tests
# Build directory: /opt/lxl/c++/logAnalyzer/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(src_config_CLIConfig_InputOutput "/opt/lxl/c++/logAnalyzer/tests/src_config_CLIConfig_InputOutput")
set_tests_properties(src_config_CLIConfig_InputOutput PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CLIConfig_Filtering "/opt/lxl/c++/logAnalyzer/tests/src_config_CLIConfig_Filtering")
set_tests_properties(src_config_CLIConfig_Filtering PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CLIConfig_Formatting "/opt/lxl/c++/logAnalyzer/tests/src_config_CLIConfig_Formatting")
set_tests_properties(src_config_CLIConfig_Formatting PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CLIConfig_Analysis "/opt/lxl/c++/logAnalyzer/tests/src_config_CLIConfig_Analysis")
set_tests_properties(src_config_CLIConfig_Analysis PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CLIConfig_Errors "/opt/lxl/c++/logAnalyzer/tests/src_config_CLIConfig_Errors")
set_tests_properties(src_config_CLIConfig_Errors PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CLIConfig_Defaults "/opt/lxl/c++/logAnalyzer/tests/src_config_CLIConfig_Defaults")
set_tests_properties(src_config_CLIConfig_Defaults PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CoreBasic "/opt/lxl/c++/logAnalyzer/tests/src_config_CoreBasic")
set_tests_properties(src_config_CoreBasic PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CoreJson "/opt/lxl/c++/logAnalyzer/tests/src_config_CoreJson")
set_tests_properties(src_config_CoreJson PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CoreValidation "/opt/lxl/c++/logAnalyzer/tests/src_config_CoreValidation")
set_tests_properties(src_config_CoreValidation PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_config_CoreFeatures "/opt/lxl/c++/logAnalyzer/tests/src_config_CoreFeatures")
set_tests_properties(src_config_CoreFeatures PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_core_LogParser "/opt/lxl/c++/logAnalyzer/tests/src_core_LogParser")
set_tests_properties(src_core_LogParser PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_core_LogTypes "/opt/lxl/c++/logAnalyzer/tests/src_core_LogTypes")
set_tests_properties(src_core_LogTypes PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_export_Core "/opt/lxl/c++/logAnalyzer/tests/src_export_Core")
set_tests_properties(src_export_Core PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_export_Json "/opt/lxl/c++/logAnalyzer/tests/src_export_Json")
set_tests_properties(src_export_Json PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_export_Csv "/opt/lxl/c++/logAnalyzer/tests/src_export_Csv")
set_tests_properties(src_export_Csv PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_export_Text "/opt/lxl/c++/logAnalyzer/tests/src_export_Text")
set_tests_properties(src_export_Text PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_export_FieldMapping "/opt/lxl/c++/logAnalyzer/tests/src_export_FieldMapping")
set_tests_properties(src_export_FieldMapping PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_export_Settings "/opt/lxl/c++/logAnalyzer/tests/src_export_Settings")
set_tests_properties(src_export_Settings PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_export_TestUtils "/opt/lxl/c++/logAnalyzer/tests/src_export_TestUtils")
set_tests_properties(src_export_TestUtils PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_analyzer_Core "/opt/lxl/c++/logAnalyzer/tests/src_analyzer_Core")
set_tests_properties(src_analyzer_Core PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_LegacyFilterTests "/opt/lxl/c++/logAnalyzer/tests/src_filter_LegacyFilterTests")
set_tests_properties(src_filter_LegacyFilterTests PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_FluentApiTests "/opt/lxl/c++/logAnalyzer/tests/src_filter_FluentApiTests")
set_tests_properties(src_filter_FluentApiTests PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_EvaluationTests "/opt/lxl/c++/logAnalyzer/tests/src_filter_EvaluationTests")
set_tests_properties(src_filter_EvaluationTests PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_LogicalNegationTests "/opt/lxl/c++/logAnalyzer/tests/src_filter_LogicalNegationTests")
set_tests_properties(src_filter_LogicalNegationTests PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_Advanced "/opt/lxl/c++/logAnalyzer/tests/src_filter_Advanced")
set_tests_properties(src_filter_Advanced PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_Version "/opt/lxl/c++/logAnalyzer/tests/src_filter_Version")
set_tests_properties(src_filter_Version PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_IpAddress "/opt/lxl/c++/logAnalyzer/tests/src_filter_IpAddress")
set_tests_properties(src_filter_IpAddress PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_CoreJsonBasic "/opt/lxl/c++/logAnalyzer/tests/src_filter_CoreJsonBasic")
set_tests_properties(src_filter_CoreJsonBasic PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_CoreJsonCondition "/opt/lxl/c++/logAnalyzer/tests/src_filter_CoreJsonCondition")
set_tests_properties(src_filter_CoreJsonCondition PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_CoreJsonExpression "/opt/lxl/c++/logAnalyzer/tests/src_filter_CoreJsonExpression")
set_tests_properties(src_filter_CoreJsonExpression PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_CoreJsonRule "/opt/lxl/c++/logAnalyzer/tests/src_filter_CoreJsonRule")
set_tests_properties(src_filter_CoreJsonRule PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_CoreUnitAdvanced "/opt/lxl/c++/logAnalyzer/tests/src_filter_CoreUnitAdvanced")
set_tests_properties(src_filter_CoreUnitAdvanced PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_CoreUnitBasic "/opt/lxl/c++/logAnalyzer/tests/src_filter_CoreUnitBasic")
set_tests_properties(src_filter_CoreUnitBasic PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_CoreUnitField "/opt/lxl/c++/logAnalyzer/tests/src_filter_CoreUnitField")
set_tests_properties(src_filter_CoreUnitField PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_Iteration2Tests "/opt/lxl/c++/logAnalyzer/tests/src_filter_Iteration2Tests")
set_tests_properties(src_filter_Iteration2Tests PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_Iteration13Tests "/opt/lxl/c++/logAnalyzer/tests/src_filter_Iteration13Tests")
set_tests_properties(src_filter_Iteration13Tests PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_filter_Iteration15Tests "/opt/lxl/c++/logAnalyzer/tests/src_filter_Iteration15Tests")
set_tests_properties(src_filter_Iteration15Tests PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_stats_Statistics "/opt/lxl/c++/logAnalyzer/tests/src_stats_Statistics")
set_tests_properties(src_stats_Statistics PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_utils_Time "/opt/lxl/c++/logAnalyzer/tests/src_utils_Time")
set_tests_properties(src_utils_Time PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_utils_Enum "/opt/lxl/c++/logAnalyzer/tests/src_utils_Enum")
set_tests_properties(src_utils_Enum PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_utils_String "/opt/lxl/c++/logAnalyzer/tests/src_utils_String")
set_tests_properties(src_utils_String PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_analyzer_Types_test "/opt/lxl/c++/logAnalyzer/tests/src_analyzer_Types_test")
set_tests_properties(src_analyzer_Types_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(src_analyzer_LogWriter_test "/opt/lxl/c++/logAnalyzer/tests/src_analyzer_LogWriter_test")
set_tests_properties(src_analyzer_LogWriter_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
