# CMake generated Testfile for 
# Source directory: /opt/lxl/c++/logAnalyzer/tests
# Build directory: /opt/lxl/c++/logAnalyzer/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(config_CLIConfig_InputOutput "/opt/lxl/c++/logAnalyzer/tests/config_CLIConfig_InputOutput")
set_tests_properties(config_CLIConfig_InputOutput PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CLIConfig_Filtering "/opt/lxl/c++/logAnalyzer/tests/config_CLIConfig_Filtering")
set_tests_properties(config_CLIConfig_Filtering PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CLIConfig_Formatting "/opt/lxl/c++/logAnalyzer/tests/config_CLIConfig_Formatting")
set_tests_properties(config_CLIConfig_Formatting PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CLIConfig_Analysis "/opt/lxl/c++/logAnalyzer/tests/config_CLIConfig_Analysis")
set_tests_properties(config_CLIConfig_Analysis PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CLIConfig_Errors "/opt/lxl/c++/logAnalyzer/tests/config_CLIConfig_Errors")
set_tests_properties(config_CLIConfig_Errors PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CLIConfig_Defaults "/opt/lxl/c++/logAnalyzer/tests/config_CLIConfig_Defaults")
set_tests_properties(config_CLIConfig_Defaults PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CoreBasic "/opt/lxl/c++/logAnalyzer/tests/config_CoreBasic")
set_tests_properties(config_CoreBasic PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CoreJson "/opt/lxl/c++/logAnalyzer/tests/config_CoreJson")
set_tests_properties(config_CoreJson PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CoreValidation "/opt/lxl/c++/logAnalyzer/tests/config_CoreValidation")
set_tests_properties(config_CoreValidation PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_CoreFeatures "/opt/lxl/c++/logAnalyzer/tests/config_CoreFeatures")
set_tests_properties(config_CoreFeatures PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(config_Utils "/opt/lxl/c++/logAnalyzer/tests/config_Utils")
set_tests_properties(config_Utils PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(core_LogParser "/opt/lxl/c++/logAnalyzer/tests/core_LogParser")
set_tests_properties(core_LogParser PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(core_LogTypes "/opt/lxl/c++/logAnalyzer/tests/core_LogTypes")
set_tests_properties(core_LogTypes PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(export_Core "/opt/lxl/c++/logAnalyzer/tests/export_Core")
set_tests_properties(export_Core PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(export_Json "/opt/lxl/c++/logAnalyzer/tests/export_Json")
set_tests_properties(export_Json PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(export_Csv "/opt/lxl/c++/logAnalyzer/tests/export_Csv")
set_tests_properties(export_Csv PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(export_Text "/opt/lxl/c++/logAnalyzer/tests/export_Text")
set_tests_properties(export_Text PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(export_FieldMapping "/opt/lxl/c++/logAnalyzer/tests/export_FieldMapping")
set_tests_properties(export_FieldMapping PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(export_Settings "/opt/lxl/c++/logAnalyzer/tests/export_Settings")
set_tests_properties(export_Settings PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(export_TestUtils "/opt/lxl/c++/logAnalyzer/tests/export_TestUtils")
set_tests_properties(export_TestUtils PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(analyzer_Core "/opt/lxl/c++/logAnalyzer/tests/analyzer_Core")
set_tests_properties(analyzer_Core PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_LegacyFilter "/opt/lxl/c++/logAnalyzer/tests/filter_LegacyFilter")
set_tests_properties(filter_LegacyFilter PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_FluentApi "/opt/lxl/c++/logAnalyzer/tests/filter_FluentApi")
set_tests_properties(filter_FluentApi PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_Evaluation "/opt/lxl/c++/logAnalyzer/tests/filter_Evaluation")
set_tests_properties(filter_Evaluation PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_LogicalNegation "/opt/lxl/c++/logAnalyzer/tests/filter_LogicalNegation")
set_tests_properties(filter_LogicalNegation PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_Advanced "/opt/lxl/c++/logAnalyzer/tests/filter_Advanced")
set_tests_properties(filter_Advanced PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_Version "/opt/lxl/c++/logAnalyzer/tests/filter_Version")
set_tests_properties(filter_Version PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_IpAddress "/opt/lxl/c++/logAnalyzer/tests/filter_IpAddress")
set_tests_properties(filter_IpAddress PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_CoreJsonBasic "/opt/lxl/c++/logAnalyzer/tests/filter_CoreJsonBasic")
set_tests_properties(filter_CoreJsonBasic PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_CoreJsonCondition "/opt/lxl/c++/logAnalyzer/tests/filter_CoreJsonCondition")
set_tests_properties(filter_CoreJsonCondition PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_CoreJsonExpression "/opt/lxl/c++/logAnalyzer/tests/filter_CoreJsonExpression")
set_tests_properties(filter_CoreJsonExpression PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_CoreJsonRule "/opt/lxl/c++/logAnalyzer/tests/filter_CoreJsonRule")
set_tests_properties(filter_CoreJsonRule PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_CoreUnitAdvanced "/opt/lxl/c++/logAnalyzer/tests/filter_CoreUnitAdvanced")
set_tests_properties(filter_CoreUnitAdvanced PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_CoreUnitBasic "/opt/lxl/c++/logAnalyzer/tests/filter_CoreUnitBasic")
set_tests_properties(filter_CoreUnitBasic PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_CoreUnitField "/opt/lxl/c++/logAnalyzer/tests/filter_CoreUnitField")
set_tests_properties(filter_CoreUnitField PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_Iteration2 "/opt/lxl/c++/logAnalyzer/tests/filter_Iteration2")
set_tests_properties(filter_Iteration2 PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_Iteration13 "/opt/lxl/c++/logAnalyzer/tests/filter_Iteration13")
set_tests_properties(filter_Iteration13 PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(filter_Iteration15 "/opt/lxl/c++/logAnalyzer/tests/filter_Iteration15")
set_tests_properties(filter_Iteration15 PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(stats_Core "/opt/lxl/c++/logAnalyzer/tests/stats_Core")
set_tests_properties(stats_Core PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(utils_Time "/opt/lxl/c++/logAnalyzer/tests/utils_Time")
set_tests_properties(utils_Time PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(utils_Enum "/opt/lxl/c++/logAnalyzer/tests/utils_Enum")
set_tests_properties(utils_Enum PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(utils_String "/opt/lxl/c++/logAnalyzer/tests/utils_String")
set_tests_properties(utils_String PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(analyzer_Types "/opt/lxl/c++/logAnalyzer/tests/analyzer_Types")
set_tests_properties(analyzer_Types PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
add_test(analyzer_LogWriter "/opt/lxl/c++/logAnalyzer/tests/analyzer_LogWriter")
set_tests_properties(analyzer_LogWriter PROPERTIES  _BACKTRACE_TRIPLES "/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;118;add_test;/opt/lxl/c++/logAnalyzer/tests/CMakeLists.txt;0;")
